apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: seungjunjeong/nodeapp:1.1 # Docker Hub에 푸시한 이미지
          imagePullPolicy: Always # 항상 이미지를 다시 가져오도록 설정
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # 브라우저에서 http://<노드IP>:30080 으로 접근 가능
