FROM ubuntu:22.04

# 필수 패키지 설치
RUN apt-get clean && rm -rf /var/lib/apt/lists/* \
    && apt-get update \
    && apt-get install -y curl gnupg

# Node.js 설치
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# 앱 디렉토리 생성
WORKDIR /app

# 로컬 파일을 컨테이너로 복사
COPY package*.json ./
COPY app.js /app/
COPY postListPage.html /app/

RUN npm install

COPY . .

# 포트 오픈
EXPOSE 80

# 앱 실행
CMD ["node", "app.js"]

